### PR TITLE
Fix how permission level is being set

### LINKED ISSUE #107: Bug/CreateUser and UpdateUser should not allow setting permission level
## Description
By default `CreateUser`, should only create a user with a minimum `permission_level` of `NoPermission`

~~By default `UpdateUser`, should NOT alter the `permission_level` of a User unless an email update was performed thus setting  the `permission_level` of the current user to `NoPermission`~~

Once the user's email is verified, permission is set to `User`

## DOD
- [x] modified `CreateUser`
- ~~[ ] modified `UpdateUser`~~
- [x] modified `VerifiedEmailToken`

### PR DESCRIPTION
**Pull request by kimlisa**
closes #107 

VerifyEmailToken will change again for issue #108 

- CreateUser defaults permission level to NO_PERM
- implemented and unit tested updatePermissionLevel db utility
- renamed secretLocker to readSecretLocker
- renamed tokenLocker to keyGenLocker
- VerifyEmailToken updates permission level if token is valid
- updated CreateUser and VerifyEmailToken unit test to include testing for permission level changes

### CODE REVIEW

File: service/service.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ const (
 var (
 	serviceStateLocker stateLocker
 	uuidMapLocker      sync.Map
-	secretLocker       sync.RWMutex
+	readSecretLocker   sync.RWMutex
```
Comment (faraonc) [inline service/service.go]: `secretLocker` was actually a good name IMO
